site_name: FIIT Org
site_description: Making Cents

repo_url: https://github.com/fiit-org/fiit-org.github.io
repo_name: fiit-org/fiit-org.github.io

nav:
  - Home: index.md
  - Software:
      - software/index.md
      - Applications:
        - Analytics: software/analytics.md
        - DataOps: software/dataops.md
        - Platforms: software/platforms.md
      - Environments: 
        - Containers: software/containers.md
        - OS: software/os.md

theme:
  name: material
  palette:
      scheme: slate
      primary: orange
      accent: deep orange    
  icon:
    logo: simple/iota
    repo: fontawesome/brands/git
  features:
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - minify:
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
          remove_comments: true
      #js_files:
      #    - assets/js/main.js
      #css_files:
      #    - assets/css/style.css

extra:
  generator: false